name = "PQXDH-lean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PQXDHLean"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[require]]
name = "VCVio"
git = "https://github.com/Verified-zkEVM/VCV-io.git"
rev = "ebea2fa"

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso.git"
rev = "af9f9b2a4ded35975794530858214271293e34ce"

[[lean_lib]]
name = "PQXDHLean"
