name = "PQXDHDocs"
defaultTargets = ["PQXDHDocs", "docs"]

[[require]]
name = "versoBlueprint"
git = "https://github.com/ejgallego/verso-blueprint"
rev = "main"

[[lean_lib]]
name = "PQXDHDocs"

[[lean_exe]]
name = "docs"
root = "Main"
